// Code generated by goctl. DO NOT EDIT.
package types

type OrderReq struct {
	Id string `path:"id"`
}

type OrderReply struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}

type AddUserReq struct {
	Id string `path:"id"`
}

type AddUserReply struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}
